name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' 
        java-version: '17'  

    # - name: Cache Gradle packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.gradle/caches
    #     key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    #     restore-keys: |
    #       gradle-${{ runner.os }}-

    - name: Build and Test
      run: ./gradlew clean test
